package com.example.demo.entity;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Thu Jul 27 14:44:14 JST 2023
     */
    int updateByPrimaryKey(Employee record);
    
    // Add
	/**
	 * 全Employeeを取得
	 * 
	 * @return 全Employeeの情報
	 * 
	 */
	List<Employee> selectAll();
	
}